// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwkZcie6xK65wCI6jotY6QDzorgKBrLes',
    appId: '1:361127960645:web:9a8ecf95599ee27023832c',
    messagingSenderId: '361127960645',
    projectId: 'flutter-chat-app-62203',
    authDomain: 'flutter-chat-app-62203.firebaseapp.com',
    storageBucket: 'flutter-chat-app-62203.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2fGXJtnRDR-UweCJEJ5Pezfg5Jia07Z4',
    appId: '1:361127960645:android:9a5a758d33ac022223832c',
    messagingSenderId: '361127960645',
    projectId: 'flutter-chat-app-62203',
    storageBucket: 'flutter-chat-app-62203.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4cZU3NMlXY6JTTnQ5rFIu0DXjzj80WqY',
    appId: '1:361127960645:ios:5b24e7cbd8cfa2ab23832c',
    messagingSenderId: '361127960645',
    projectId: 'flutter-chat-app-62203',
    storageBucket: 'flutter-chat-app-62203.appspot.com',
    androidClientId: '361127960645-n0qttj3189mcfpn81fjp33f4n1ln2f5v.apps.googleusercontent.com',
    iosClientId: '361127960645-kmolvhbjf5cacjs4gnko04l9dkucffb3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4cZU3NMlXY6JTTnQ5rFIu0DXjzj80WqY',
    appId: '1:361127960645:ios:5b24e7cbd8cfa2ab23832c',
    messagingSenderId: '361127960645',
    projectId: 'flutter-chat-app-62203',
    storageBucket: 'flutter-chat-app-62203.appspot.com',
    androidClientId: '361127960645-n0qttj3189mcfpn81fjp33f4n1ln2f5v.apps.googleusercontent.com',
    iosClientId: '361127960645-kmolvhbjf5cacjs4gnko04l9dkucffb3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
